export const itineraryData = {
	title: "岡山五日遊",
	coverImage:
		"https://hk.wamazing.com/media/wp-content/uploads/sites/5/2024/05/kurashiki_pixta_78481820_M-853x569.jpg.webp",
	days: [
		{
			id: 1,
			date: "6/8(日)",
			title: "抵達岡山",
			theme: "arrival",
			activities: [
				{
					time: "15:05",
					title: "入境＋領行李",
					type: "transport",
					note: "",
				},
				{
					time: "16:00",
					title: "機場巴士 → 岡山站",
					type: "transport",
					note: "約 30 分, ¥780 班次 16:05",
				},
				{
					time: "16:45",
					title: "抵達岡山站 → 飯店 check-in",
					type: "accommodation",
					note: "",
				},
				{
					time: "18:00",
					title: "用餐",
					type: "dining",
					note: "吾妻壽司、味司野村",
				},
				{
					time: "19:30",
					title: "Aeon Mall 、地下街、唐吉軻德",
					type: "shopping",
					note: "",
				},
			],
		},
		{
			id: 2,
			date: "6/9(一)",
			title: "小豆島一日遊",
			theme: "island",
			activities: [
				{
					time: "07:33",
					title: "岡山車站 → 新岡山港",
					type: "transport",
					note: "搭乘新岡山港線約37分鐘 ¥500/人",
				},
				{
					time: "08:40",
					title: "新岡山港 → 土庄港",
					type: "transport",
					note: "航程約 70 分 ¥1,200/人",
				},
				{
					time: "09:50",
					title: "抵達土庄港 → 土莊港觀光中心登記",
					type: "sightseeing",
					note: "搭乘「海島遊觀光巴士」開始行程 ¥9,800/人 (已預定)",
				},
				{
					time: "10:10",
					title: "小豆島觀光巴士",
					type: "sightseeing",
					note: "銚子溪猴子之國、寒霞溪、24隻眼睛電影村、橄欖公園等",
				},
				{
					time: "16:30",
					title: "返回土庄港",
					type: "transport",
					note: "搭 17:00 或 18:30 船班返程",
				},
				{
					time: "17:00",
					title: "土庄港 → 新岡山港 → 岡山",
					type: "transport",
					note: "同去程",
				},
			],
		},
		{
			id: 3,
			date: "6/10（二）",
			title: "倉敷美觀一日遊",
			theme: "historic",
			activities: [
				{
					time: "08:40",
					title: "JR 岡山站 → 倉敷站",
					type: "transport",
					note: "JR 山陽本線，約 17 分 ¥330 8:41, 9:03, 9:16",
				},
				{
					time: "09:00",
					title: "倉敷站 → 倉敷館觀光導覽所購票",
					type: "sightseeing",
					note: "12分鐘",
				},
				{
					time: "09:30",
					title: "倉敷川游船",
					type: "activity",
					note: "半小時一班 ¥500/人",
				},
				{
					time: "10:00",
					title: "阿智神社遠眺倉敷",
					type: "sightseeing",
					note: "",
				},
				{
					time: "11:30",
					title: "午餐",
					type: "dining",
					note: "",
				},
				{
					time: "12:00",
					title: "美觀地區散策",
					type: "sightseeing",
					note: "店家營業 10:00~17:30 倉敷川老街、星巴克古民家、倉敷咖啡館琥珀女王",
				},
				{
					time: "15:30",
					title: "倉敷站 → 岡山站",
					type: "transport",
					note: "回程列車同上",
				},
			],
		},
		{
			id: 4,
			date: "6/11(三)",
			title: "香川高松一日遊",
			theme: "cultural",
			activities: [
				{
					time: "08:00",
					title: "飯店早餐（岡山）",
					type: "dining",
					note: "06:30~10:00",
				},
				{
					time: "09:05",
					title: "岡山站 → 高松站",
					type: "transport",
					note: "約1小時 Marine Liner 普通座，¥1660/人 08:40, 09:05",
				},
				{
					time: "10:05",
					title: "玉藻公園（高松城跡）",
					type: "sightseeing",
					note: "約4分鐘 ¥200/人",
				},
				{
					time: "10:40",
					title: "Symbol Tower 展望台 29F,30F",
					type: "sightseeing",
					note: "開放時間 10:00~11:00",
				},
				{
					time: "11:00",
					title: "栗林公園",
					type: "sightseeing",
					note: "",
				},
				{
					time: "11:30",
					title: "讚岐烏龍麵上原屋本店",
					type: "dining",
					note: "9:30~14:30 營業時間",
				},
				{
					time: "16:00",
					title: "高松站 → 岡山站",
					type: "transport",
					note: "同去程 16:10, 16:40, 17:10",
				},
			],
		},
		{
			id: 5,
			date: "6/12(四)",
			title: "岡山半日遊 + 回台灣",
			theme: "departure",
			activities: [
				{
					time: "09:00",
					title: "寄放行李",
					type: "accommodation",
					note: "",
				},
				{
					time: "09:10",
					title: "岡山站前 → 城下",
					type: "transport",
					note: "車程 4 分, 車資 ¥120/人",
				},
				{
					time: "09:30",
					title: "岡山城 + 後樂園 散策",
					type: "sightseeing",
					note: "約 1.5～2 小時",
				},
				{
					time: "11:00",
					title: "城下 → 岡山站前",
					type: "transport",
					note: "同去程",
				},
				{
					time: "11:30",
					title: "午餐",
					type: "dining",
					note: "",
				},
				{
					time: "14:00",
					title: "取行李 & 前往機場巴士乘車點",
					type: "transport",
					note: "排巴士",
				},
				{
					time: "15:00",
					title: "岡山站西口21號乘車處 - 岡山機場",
					type: "transport",
					note: "15:30 30分鐘直達",
				},
				{
					time: "15:40",
					title: "機場報到、安檢",
					type: "transport",
					note: "購物",
				},
				{
					time: "17:55",
					title: "✈️ 岡山機場起飛",
					type: "transport",
					note: "桃園時間 20:00 抵達",
				},
			],
		},
	],
};

// 主題顏色配置
export const themeColors = {
	arrival: {
		primary: "bg-gradient-to-r from-blue-500 to-blue-600",
		light: "bg-blue-50",
		border: "border-blue-200",
		text: "text-blue-700",
		icon: "text-blue-500",
		accent: "bg-blue-100",
	},
	island: {
		primary: "bg-gradient-to-r from-teal-500 to-cyan-600",
		light: "bg-teal-50",
		border: "border-teal-200",
		text: "text-teal-700",
		icon: "text-teal-500",
		accent: "bg-teal-100",
	},
	historic: {
		primary: "bg-gradient-to-r from-orange-400 to-orange-600",
		light: "bg-amber-50",
		border: "border-amber-200",
		text: "text-amber-700",
		icon: "text-amber-500",
		accent: "bg-amber-100",
	},
	cultural: {
		primary: "bg-gradient-to-r from-purple-500 to-purple-600",
		light: "bg-purple-50",
		border: "border-purple-200",
		text: "text-purple-700",
		icon: "text-purple-500",
		accent: "bg-purple-100",
	},
	departure: {
		primary: "bg-gradient-to-r from-rose-500 to-pink-600",
		light: "bg-rose-50",
		border: "border-rose-200",
		text: "text-rose-700",
		icon: "text-rose-500",
		accent: "bg-rose-100",
	},
};
